### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by rounk-ctrl** [echnobas/sxsc#4]
![image](https://github.com/echnobas/sxsc/assets/70931017/ec7d307c-7b3b-4ccf-b025-95c2aea9930c)
windows 11 build 23565

and no i didnt touch windows update components at all

**Comment by echnobas** [comment]
does https://github.com/echnobas/sxs_offender work

**Comment by rounk-ctrl** [comment]
nope

**Comment by echnobas** [comment]
Ignore those errors, it looks like defender is locking the keys. Not entirely sure why, I'll investigate later.

**Comment by echnobas** [comment]
> Ignore those errors, it looks like defender is locking the keys. Not entirely sure why, I'll investigate later.

Try booting it into safe mode then trying again

**Comment by rounk-ctrl** [comment]
didnt help, same error

**Comment by echnobas** [comment]
![image](https://github.com/echnobas/sxsc/assets/60543166/66223cab-a130-42ce-bf82-dd0bf465e669)
![image](https://github.com/echnobas/sxsc/assets/60543166/10351f4a-2bd8-4c96-b1e6-ca4ed69e3a7f)

is this iso from uupdump, i remember some issues with those? a quick test on 23H2 shows it still works. i can't think of any other solution to your problem other than installing the package manually from winre.

iso i used
https://oemsoc.download.prss.microsoft.com/dbazure/X23-59469_22631.2428.231001-0608.23H2_NI_RELEASE_SVC_REFRESH_CLIENTENTERPRISE_OEM_x64FRE_en-us.iso_98e93382-2a6d-4458-811b-386a8ec8f38d?t=8afc61e4-8d02-49e4-ae48-949d561afd96&e=102787652286&h=a4c1d73ed485d7378ba13f19ba49f9fa2a3553e28bfda4a93950aea451f0f6ad

**Comment by rounk-ctrl** [comment]
and how do i build a package? there are no documentations for it

**Comment by echnobas** [comment]
> so i installed a canary build and sxs_offender worked, while this repo didnt work

sxs_offender uses a newer version of the package, trying to install 1.0.0.0 (this repo) after installing 1.0.0.3 (sxs_offender) will not work.

> and how do i build a package? there are no documentations for it
Run sxsc.py then build.bat to build the package defined in cfg.yaml

**Comment by rounk-ctrl** [comment]
btw can we make this thing generate a update file that updates the file with a custom file, instead of nuking it
